- name: copying rsp file for database creation
  copy:
    src: ./rsp/dbcavirtualbox.rsp
    dest: /u01/dbcavirtualbox.rsp
    owner: oracle
    group: oinstall
    mode: 0644

- name: Run database creation
  command: /u01/app/oracle/product/12.2.0.1/db_home1/bin/dbca -silent -createDatabase -responseFile /u01/dbcavirtualbox.rsp
  args:
    creates: /u01/app/oracle/cfgtoollogs/dbca/orcl
  become: yes
  become_user: oracle

- name: Run oracle installation post task 2/2
  command: /u01/app/oracle/product/12.2.0.1/db_home1/root.sh

